### ISSUE TITLE
Bucket Lifecycle Prefix is not applied

### ISSUE THREAD

**Issue by smoench** [ionos-cloud/terraform-provider-ionoscloud#780]
## Description
While applying a bucket lifecycle configuration, the rule prefix is not applied but the rule is applied for the whole bucket. Applying the prefix via DCD works.

## Expected behavior
The rule prefix gets correctly applied.

## Environment

Terraform version: 
```
v1.10.5
```
Provider version: 
```
v6.7.2
```
OS:
```
MacOS 15
```

## Additional Notes

I think there is a mismatch between the documented API Definition and the actual API Implementation.
While the documented API definition says the prefix needs to be in the `<Rule><Prefix>logs/</Prefix></Rule>` but the request sample says it must be in `<Rule><Filter><Prefix>logs/</Prefix></Filter></Rule>`.

Documented API Definition
![Image](https://github.com/user-attachments/assets/12a27322-05db-44ae-9908-c926ea49277b)

Request Sample
![Image](https://github.com/user-attachments/assets/c5236610-8098-4d88-ac38-5996abf231db)

-> https://api.ionos.com/docs/object-storage-contract-owned-buckets/v2/#tag/Lifecycle/operation/PutBucketLifecycle

**Comment by cristiGuranIonos** [comment]
Thanks for raising this, from what we investigated: 
Documentation is stating that Prefix is required, but actually it is not. Filter is required.

We will fix this.

**Comment by smoench** [comment]
Is this planned to be fixed anytime soon? We would like to configure it via terraform :-)

**Comment by cristiGuranIonos** [comment]
I think the docs were fixed for this.

**Comment by smoench** [comment]
terraform resource `ionoscloud_s3_bucket_lifecycle_configuration` still does not support/applies prefix, so instead it is applied for the whole bucket.

**Comment by cristiGuranIonos** [comment]
Should be fixed in v6.7.9  Sorry for the delay, we had to do a workaround because the spec is still not fixed so it took longer.
